# Generated by Django 2.2.6 on 2021-01-06 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='sub_category',
            new_name='name',
        ),
    ]
