# Generated by Django 2.2.6 on 2021-01-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210106_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=500)),
                ('sub_category', models.CharField(max_length=500)),
            ],
        ),
    ]
